In [1]:
from pylab import plt, mpl
import os
plt.style.use('seaborn-v0_8')
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

In [2]:
import pickle 
import numpy as np
from random import gauss

In [3]:
a = [gauss(1.5, 2) for i in range(1000000)]

In [4]:
path = './data/'

In [5]:
os.makedirs(os.path.dirname(path + 'data.pkl'), exist_ok=True)

<span style='font-size:17px'><b>Data Generation and Environment Setup</b>

* <b>Environment:</b> Imports the 'pylab', 'os', and 'pickle' modules while setting the global style to 'seaborn-v0-8' and the font family to 'serif'.
* <b>Generation:</b> Creates a synthetic dataset 'a' containing one million Gaussian random numbers with a mean ($\mu$) of 1.5 and a standard deviation ($\sigma$) of 2.
* <b>Infrastructure:</b> Defines a local storage path and uses 'os.makedirs' to ensure the directory exists before any ''pickle' serialization or I/O operations take place.

In [6]:
pkl_file = open(path + 'data.pkl', 'wb')

In [7]:
%time pickle.dump(a, pkl_file)

CPU times: total: 31.2 ms
Wall time: 28.1 ms


In [8]:
pkl_file.close()

In [9]:
!dir {path.replace("/", "\\")}

 Volume in drive C is OS
 Volume Serial Number is 4A66-C709

 Directory of C:\Users\wyatt\anaconda_projects\a6d78ae2-3898-4b7b-84be-fb1978404837\data

02/26/2026  11:08 AM    <DIR>          .
02/26/2026  11:22 AM    <DIR>          ..
02/26/2026  11:22 AM           252,830 data.csv
02/26/2026  11:23 AM         9,003,247 data.pkl
               2 File(s)      9,256,077 bytes
               2 Dir(s)  320,009,236,480 bytes free


In [10]:
f = open(path + 'data.pkl', 'rb')
b = pickle.load(f)
f.close()

In [11]:
a[:3]

[-1.5393964764965924, -0.2726211951836832, 4.0127901030672]

In [12]:
b[:3]

[-1.5393964764965924, -0.2726211951836832, 4.0127901030672]

In [13]:
np.allclose(np.array(a), np.array(b))

True

<span style='font-size:17px'><b>Data Serialization: Python Pickle Module</b>

* <b>Saving:</b> Opens a file handle in 'write-binary' ('wb') mode and 'pickle.dump' to serialize the list object to the disk.
* <b>Inspection:</b> Uses a shell command to verify the file creation and size, confirming approximately 9 MB of data was written.
* <b>Loading:</b> Reopens the file in 'read-binary' ('rb') mode to deserialize the data back into a new Python object 'b'.
* <b>Validation:</b> Compares the first few elements and uses 'np.allclose' to verify that the reconstructed data is identical to the original.

In [14]:
pkl_file = open(path + 'data.pkl', 'wb')

In [15]:
%time pickle.dump(np.array(a), pkl_file)

CPU times: total: 62.5 ms
Wall time: 80.3 ms


In [16]:
%time pickle.dump(np.array(a)**2, pkl_file)

CPU times: total: 78.1 ms
Wall time: 89.5 ms


In [17]:
pkl_file.close()

In [18]:
!dir {path.replace("/", "\\")}

 Volume in drive C is OS
 Volume Serial Number is 4A66-C709

 Directory of C:\Users\wyatt\anaconda_projects\a6d78ae2-3898-4b7b-84be-fb1978404837\data

02/26/2026  11:08 AM    <DIR>          .
02/26/2026  11:22 AM    <DIR>          ..
02/26/2026  11:22 AM           252,830 data.csv
02/26/2026  11:23 AM        16,000,326 data.pkl
               2 File(s)     16,253,156 bytes
               2 Dir(s)  320,002,240,512 bytes free


In [19]:
pkl_file = open(path + 'data.pkl', 'rb')

In [20]:
x = pickle.load(pkl_file)
x[:4]

array([-1.53939648, -0.2726212 ,  4.0127901 , -0.87913734])

In [21]:
y = pickle.load(pkl_file)
y[:4]

array([ 2.36974151,  0.07432232, 16.10248441,  0.77288247])

In [22]:
pkl_file.close()

In [23]:
pkl_file = open (path + 'data.pkl', 'wb')
pickle.dump({'x': x, 'y': y}, pkl_file)
pkl_file.close()

In [24]:
pkl_file = open(path + 'data.pkl', 'rb')
data = pickle.load(pkl_file)
pkl_file.close()
for key in data.keys():
    print(key, data[key][:4])

x [-1.53939648 -0.2726212   4.0127901  -0.87913734]
y [ 2.36974151  0.07432232 16.10248441  0.77288247]


<span style='font-size:17px'>Data Serialization: NumpPy Arrays and Dicts

* <b>Array Storage:</b> Serializes multiple 'NumPy' arrays into a single pickle file, demonstrating the efficient storage of numerical data structures.
* <b>Sequential Loading:</b> Uses repeated 'pickle.load' calls to retrieve multiple objects from a single fiel in the exact order they were written.
* <b>Dictionary Mapping:</b> Implements a more robust storage method by wrapping multiple arrays into a 'dict' (e.g., '{'x': x, 'y': y}'), allowing for keyed data retrieval.
* <b>Verification:</b> Iterates through the stored keys to confirm that the data structure and numerical values remain intact after deserialization.

In [25]:
import pandas as pd

In [26]:
rows = 5000
a = np.random.standard_normal((rows, 5)).round(4)

In [27]:
a 

array([[-0.982 ,  0.1788,  1.952 , -2.7041,  0.2406],
       [-1.2299, -0.2773,  0.189 ,  0.0224,  1.883 ],
       [ 0.4971,  1.4105,  0.7528, -1.5607,  0.6531],
       ...,
       [ 2.1285,  1.1607, -0.6004,  0.234 , -0.7088],
       [ 0.8234, -1.3169, -0.9332, -1.6274,  1.5917],
       [ 0.1391,  0.1476,  0.1565, -0.9225,  0.7422]])

In [28]:
t = pd.date_range(start='2019/1/1', periods=rows, freq='H')

C:\Users\wyatt\AppData\Local\Temp\ipykernel_8588\4267316154.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  t = pd.date_range(start='2019/1/1', periods=rows, freq='H')


In [29]:
t

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               ...
               '2019-07-27 22:00:00', '2019-07-27 23:00:00',
               '2019-07-28 00:00:00', '2019-07-28 01:00:00',
               '2019-07-28 02:00:00', '2019-07-28 03:00:00',
               '2019-07-28 04:00:00', '2019-07-28 05:00:00',
               '2019-07-28 06:00:00', '2019-07-28 07:00:00'],
              dtype='datetime64[ns]', length=5000, freq='h')

In [69]:
csv_file = open(path + 'data.csv','w')

In [70]:
header = 'date, no1, no2, no3, no4, no5\n'

In [71]:
csv_file.write(header)

30

In [72]:
for t_, (no1, no2, no3, no4, no5) in zip(t, a): 
    s = '{},{},{},{},{},{}\n'.format(t_, no1, no2, no3, no4, no5)
    csv_file.write(s)

In [73]:
csv_file.close()

In [74]:
!dir {path.replace("/", "\\")}

 Volume in drive C is OS
 Volume Serial Number is 4A66-C709

 Directory of C:\Users\wyatt\anaconda_projects\a6d78ae2-3898-4b7b-84be-fb1978404837\data

02/26/2026  11:08 AM    <DIR>          .
02/26/2026  11:44 AM    <DIR>          ..
02/26/2026  11:44 AM           289,677 data.csv
02/26/2026  11:23 AM        16,000,254 data.pkl
               2 File(s)     16,289,931 bytes
               2 Dir(s)  319,785,476,096 bytes free


<span style='font-size:17px'><b>Data Generation</b>

* <b>NumPy Generation:</b> Creates a $5000 \times 5$ array of standard normal random numbers rounded to four decimal places for financial modeling simulation.
* <b>Datetime Indexing:</b> Generates a 'DatetimeIndex' starting from 2019-01-01 with an hourly frequency to serve as the temporal backbone for the dataset.
* <b>CSV Infrastructure:</b> Initializes a new CSV file and manually writes a header string to define the data columns ('date','no1', 'no2', etc.).
* <b>Manual Serialization:</b> Iterates through the zipped datetime and numerical data, formatting each row as a string to be written directly to the disk.

In [75]:
csv_file = open(path + 'data.csv', 'r')

In [76]:
for i in range(5):
    print(csv_file.readline(), end='')

date, no1, no2, no3, no4, no5
2019-01-01 00:00:00,-0.982,0.1788,1.952,-2.7041,0.2406
2019-01-01 01:00:00,-1.2299,-0.2773,0.189,0.0224,1.883
2019-01-01 02:00:00,0.4971,1.4105,0.7528,-1.5607,0.6531
2019-01-01 03:00:00,-0.2409,0.9284,-0.0151,-2.1971,0.9428


In [77]:
csv_file.close()

In [78]:
csv_file = open(path + 'data.csv', 'r')

In [79]:
content = csv_file.readlines()

In [80]:
content[:5]

['date, no1, no2, no3, no4, no5\n',
 '2019-01-01 00:00:00,-0.982,0.1788,1.952,-2.7041,0.2406\n',
 '2019-01-01 01:00:00,-1.2299,-0.2773,0.189,0.0224,1.883\n',
 '2019-01-01 02:00:00,0.4971,1.4105,0.7528,-1.5607,0.6531\n',
 '2019-01-01 03:00:00,-0.2409,0.9284,-0.0151,-2.1971,0.9428\n']

In [81]:
csv_file.close()

<span style='font-size:17px'><b>Data Inspection: CSV File Reading</b>

* <b>Line-by-Line:</b> Opens the 'data.csv' file in read mode (''r'') and uses a 'for' loop with 'readline()' to print the first five lines without loading the entire file into memory.
* <b>Bulk Loading:</b> Re-opens the file to use the 'readlines()' method, which reads all lines of the file into a Python 'list' object named 'content'.
* <b>String Parsing:</b> Demonstrates how the raw data is stored as a list of strings, including the header row and subsequent data rows with newline characters ('\n').


In [82]:
import csv

In [83]:
with open(path + 'data.csv', 'r') as f:
    csv_reader = csv.reader(f)
    lines = [line for line in csv_reader]

In [84]:
lines[:5]

[['date', ' no1', ' no2', ' no3', ' no4', ' no5'],
 ['2019-01-01 00:00:00', '-0.982', '0.1788', '1.952', '-2.7041', '0.2406'],
 ['2019-01-01 01:00:00', '-1.2299', '-0.2773', '0.189', '0.0224', '1.883'],
 ['2019-01-01 02:00:00', '0.4971', '1.4105', '0.7528', '-1.5607', '0.6531'],
 ['2019-01-01 03:00:00', '-0.2409', '0.9284', '-0.0151', '-2.1971', '0.9428']]

In [85]:
with open(path + 'data.csv', 'r') as f:
    csv_reader = csv.DictReader(f)
    lines = [line for line in csv_reader]

In [86]:
lines[:3]

[{'date': '2019-01-01 00:00:00',
  ' no1': '-0.982',
  ' no2': '0.1788',
  ' no3': '1.952',
  ' no4': '-2.7041',
  ' no5': '0.2406'},
 {'date': '2019-01-01 01:00:00',
  ' no1': '-1.2299',
  ' no2': '-0.2773',
  ' no3': '0.189',
  ' no4': '0.0224',
  ' no5': '1.883'},
 {'date': '2019-01-01 02:00:00',
  ' no1': '0.4971',
  ' no2': '1.4105',
  ' no3': '0.7528',
  ' no4': '-1.5607',
  ' no5': '0.6531'}]

<span style='font-size:17px'><b>Data Retrieval: Python csv Module</b>

* <b>Standard Reader:</b> Imports the 'csv' module and uses 'csv.reader' to parse through the file into a list of lists, automatically splitting the comma-seperated strings into individual date elements.
* <b>Dictionary Reader:</b> Implements the 'csv.DictReader' to map each row of data to a dictionary, using the header row as keys for more intuitive data access.
* <b>Context Management:</b> Utilitzes the 'with open(...) as f:' statement, which ensures the file is automatically and safely closed after the code block finishes.
* <b>Data Structure:</b> Demonstrates the difference between accessing data by Index (standard reader) versus accessing it by column name (dictionary reader).

In [87]:
import sqlite3 as sq3

In [88]:
con = sq3.connect(path + 'numbs.db')

In [89]:
query = 'CREATE TABLE numbs (Date date, No1 real, No2 real)'

In [90]:
con.execute(query)

In [91]:
con.commit()

In [92]:
q = con.execute

In [94]:
q('SELECT * FROM sqlite_master').fetchall()

[('table',
  'numbs',
  'numbs',
  2,
  'CREATE TABLE numbs (Date date, No1 real, No2 real)')]

<span style='font-size:17px'><b>Data Storage: SQLite Database Integration</b>

* <b>Database Connection:</b> Imports the 'sqlite3' module and establishes a connection to a local databaser file named 'numbs.db'.
* <b>Table Creation:</b> Defines and executes a SQL query to create a structured table names 'numbs' with speciific data types for dates and numeric values .
* <b>Transaction Management:</b> Utilitizes 'con.commit()' to finalize the table creation, ensuring the changes are saved permanently to the disk.
* <b>Metadata Inspection:</b> Queries the 'sqlite_master' table to verify that the table schema has been correctly initialized within the database.

In [95]:
import datetime

In [97]:
now = datetime.datetime.now()
q('INSERT INTO numbs VALUES(?, ?, ?)', (now, 0.12, 7.3))

C:\Users\wyatt\AppData\Local\Temp\ipykernel_8588\980975171.py:2: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  q('INSERT INTO numbs VALUES(?, ?, ?)', (now, 0.12, 7.3))


In [98]:
np.random.seed(100)

In [100]:
data = np.random.standard_normal((10000, 2)).round(4)

In [103]:
%%time
for row in data:
    now = datetime.datetime.now()
    q('INSERT INTO numbs VALUES(?, ?, ?)', (now, row[0], row[1]))
con.commit()

CPU times: total: 156 ms
Wall time: 130 ms


<timed exec>:3: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes


In [104]:
q('SELECT * FROM numbs').fetchmany(4)

[('2026-02-26 12:02:15.746918', 0.12, 7.3),
 ('2026-02-26 12:04:23.559387', -1.7498, 0.3427),
 ('2026-02-26 12:04:23.559909', 1.153, -0.2524),
 ('2026-02-26 12:04:23.560032', 0.9813, 0.5142)]

In [105]:
q('SELECT * FROM numbs WHERE no1 > 0.5').fetchmany(4)

[('2026-02-26 12:04:23.559909', 1.153, -0.2524),
 ('2026-02-26 12:04:23.560032', 0.9813, 0.5142),
 ('2026-02-26 12:04:23.560426', 0.6727, -0.1044),
 ('2026-02-26 12:04:23.560497', 1.619, 1.5416)]

In [106]:
pointer = q('SELECT * FROM numbs')

In [107]:
for i in range(3):
    print(pointer.fetchone())

('2026-02-26 12:02:15.746918', 0.12, 7.3)
('2026-02-26 12:04:23.559387', -1.7498, 0.3427)
('2026-02-26 12:04:23.559909', 1.153, -0.2524)


In [108]:
rows = pointer.fetchall()
rows[:3]

[('2026-02-26 12:04:23.560032', 0.9813, 0.5142),
 ('2026-02-26 12:04:23.560048', 0.2212, -1.07),
 ('2026-02-26 12:04:23.560298', -0.1895, 0.255)]

<span style='font-size:17px'><b>SQLite: Data Insertion and Querying</b>

* <b>Single Insertion:</b> Demonstrates the basic syntax for adding a single row to the 'numbs' table using parameterized queries to handle 'datetime' objects and numerical values safely.
* <b>Bulk Operations:</b> Uses a 'for' loop to iterate through a 10,000-row NumPy array, inserting data points alongside high-resolution timestamps and committing the transaction to disk.
* <b>Data Retrieval:</b> Employs SQL 'SELECT' statements with filtering (e.g., 'WHERE no1 > 0.5') and the 'fetchmany()' method to retrieve specific subsets of the dataset.
* <b>Cursor Management:</b> Shows how to use a pointer to fetch results sequentially via 'fetchone()' or in bulk via 'fetchall()', illustrating efficient memory management when handling database results.


In [109]:
q('DROP TABLE IF EXISTS numbs')

In [110]:
q('SELECT * FROM sqlite_master').fetchall()

[]

In [111]:
con.close()

In [113]:
!dir

 Volume in drive C is OS
 Volume Serial Number is 4A66-C709

 Directory of C:\Users\wyatt\anaconda_projects\a6d78ae2-3898-4b7b-84be-fb1978404837

02/26/2026  12:23 PM    <DIR>          .
02/24/2026  04:04 PM    <DIR>          ..
02/24/2026  04:04 PM    <DIR>          .ipynb_checkpoints
02/26/2026  12:23 PM    <DIR>          data
02/26/2026  12:23 PM            32,678 Input_Output.ipynb
               1 File(s)         32,678 bytes
               4 Dir(s)  320,055,848,960 bytes free
